### PR TITLE
WIP : Bump pulsar 2.6

### PR DESCRIPTION
**Pull request by Mefl**
pulsar 2.6 comes with a new kafka compatibility feature : you can do message with null payload. ( https://github.com/apache/pulsar/commit/d55bc00f34a2fa763a3756fa0adbb1366ae319bd )

This patch is able to sent such message but it cannot consume it because it will be convert into a null msg on the stream, witch is impossible.

Before submitting a bigger patch on this subject, how do you think this should be addressed ? 

I though we can create a message container, working such as an option, and it should be be invisible for most developer but could be accessible by raw api for those who need to be able to manipulate null payload.

### CODE REVIEW

**Comment by gmethvin** [comment]
Yeah, given that the goal here is to build an idiomatic Scala library, I would definitely prefer to avoid nulls as part of the public API.

The most straightforward solution I guess would be to replace all the `T`s with `Option[T]`s. That's obviously not very nice for users who never send null messages, but it works.

Another possible solution is to extend schemas to support optional values. As I understand it, Pulsar's schema registry doesn't support enforcing the nullability or non-nullability of messages, but making the nullability aspect part of the schema would at least allow you to define in one place whether the messages are nullable. I think we'd need to wrap the Java `Schema` in that case though.

@sksamuel any specific opinions on this?

**Comment by gmethvin** [comment]
Perhaps we could split this into two parts, though. Just the required changes for 2.6.0 without null support, then the null support changes.

**Comment by Mefl** [comment]
I think we can do better than just put an option[T], I rather though about transforming the ConsumerMessage wrapper into a functor that will mask the null value : if you want to see null values, you can fold the message and have the two specifics behaviors, or if you only want to see defined values, you can map the message to work with value or have the default value with a getOrElse.

We can split it into 2 PRs if you prefer : the current is the required change for supporting 2.6, let me know if you want that I rename the PR.

**Comment by gmethvin** [comment]
@Mefl I went ahead and merged this as-is, since it's the minimum required change. @sksamuel can do the release.

**Comment by gmethvin** [comment]
I was thinking about something like what you were saying, essentially making `ConsumerMessage` a functor so you can map over the message value. That said, the important thing I think is what you actually make optional.

For example you could have:

```scala
trait ConsumerMessage[T] {
  def data: Option[MessageData[T]]
  ...
}
trait ProducerMessage[T] {
  def data: Option[MessageData[T]]
  ...
}
trait MessageData[T] {
  def value: T
  def data: Array[Byte]
}
```

Then you could certainly turn `ConsumerMessage` into a functor so you can map over the actual value.

**Comment by sksamuel** [comment]
Can release tomorrow

**Comment by sksamuel** [comment]
2.6.0 released.

**Comment by Mefl** [comment]
thank you for the merge, I will work on the second part as @gmethvin comment in few days

**Pull request merged**
