### PR TITLE
fix 183

### LINKED ISSUE #183: Starting from version 2.5.1 subscriptionInitialPosition is always Earliest
Starting from version 2.5.1 subscriptionInitialPosition is always Earliest, setting this is not working

```scala
 val consumerConfig = ConsumerConfig(
       subscriptionName = Subscription(UUID.randomUUID().toString()),
       topics = topics,
       subscriptionInitialPosition = Some(SubscriptionInitialPosition.Latest)
)
```

To reproduce just create a new consumer setting `subscriptionInitialPosition = Some(SubscriptionInitialPosition.Latest)`

Following the log created setting  `SubscriptionInitialPosition.Latest`
```
2020.05.26 16:29:05 INFO  2020-05-26 16:29:06,569 [34m  [INFO][0;39m [org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl:108]: Starting Pulsar consumer status recorder with config: {
2020.05.26 16:29:05 INFO    "topicNames" : [ "persistent://93cf4f25-a6f9-4d84-a398-1a0a12429f86/58789bc7-54b2-40eb-bc2d-3bb5eba8a342/tags/channel_1" ],
2020.05.26 16:29:05 INFO    "topicsPattern" : null,
2020.05.26 16:29:05 INFO    "subscriptionName" : "a2ba233f-b437-499b-b428-35a38241e6d9",
2020.05.26 16:29:05 INFO    "subscriptionType" : "Exclusive",
2020.05.26 16:29:05 INFO    "subscriptionMode" : "Durable",
2020.05.26 16:29:05 INFO    "receiverQueueSize" : 1000,
2020.05.26 16:29:05 INFO    "acknowledgementsGroupTimeMicros" : 100000,
2020.05.26 16:29:05 INFO    "negativeAckRedeliveryDelayMicros" : 60000000,
2020.05.26 16:29:05 INFO    "maxTotalReceiverQueueSizeAcrossPartitions" : 50000,
2020.05.26 16:29:05 INFO    "consumerName" : null,
2020.05.26 16:29:05 INFO    "ackTimeoutMillis" : 0,
2020.05.26 16:29:05 INFO    "tickDurationMillis" : 1000,
2020.05.26 16:29:05 INFO    "priorityLevel" : 0,
2020.05.26 16:29:05 INFO    "cryptoFailureAction" : "FAIL",
2020.05.26 16:29:05 INFO    "properties" : { },
2020.05.26 16:29:05 INFO    "readCompacted" : false,
2020.05.26 16:29:05 INFO    "subscriptionInitialPosition" : "Earliest",
2020.05.26 16:29:05 INFO    "patternAutoDiscoveryPeriod" : 1,
2020.05.26 16:29:05 INFO    "regexSubscriptionMode" : "PersistentOnly",
2020.05.26 16:29:05 INFO    "deadLetterPolicy" : null,
2020.05.26 16:29:05 INFO    "autoUpdatePartitions" : true,
2020.05.26 16:29:05 INFO    "replicateSubscriptionState" : false,
2020.05.26 16:29:05 INFO    "resetIncludeHead" : false,
2020.05.26 16:29:05 INFO    "keySharedPolicy" : null
2020.05.26 16:29:05 INFO  }
```

### PR DESCRIPTION
**Pull request by nicolo-paganin**
fix #183

### CODE REVIEW

**Comment by sksamuel** [comment]
Should we use a config option rather than just not setting it ?

**Comment by nicolo-paganin** [comment]
@sksamuel the `subscriptionInitialPosition` it is set here https://github.com/sksamuel/pulsar4s/blob/44c284617514d73b817e04a59d85ac89e2ea1dce/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/PulsarClient.scala#L174

I think that @cipriansofronia make a copy&paste mistake or it left that config there accidentally

**Comment by sksamuel** [comment]
Yes sorry I see.

**Comment by nicolo-paganin** [comment]
> Yes sorry I see.

What is surprising to me is that unit tests were not failing...

**Comment by sksamuel** [comment]
Probably because I changed them to be happy with the earliest thing,
without realizing.

**Pull request merged**
