### PR TITLE
Pulsar 2.5 support

### LINKED ISSUE #157: Pulsar 2.5 support
We should upgrade to Pulsar 2.5 and also make sure we support any new configurations it supports for the producer and consumer.

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #157

Adds basic support for the Pulsar 2.5 client. This doesn't support all new features, in particular batch receiving, which I created #158 for.

### CODE REVIEW

**Comment by sksamuel** [comment]
Only comment is whether you meant to remove the higher kinds language import flag.

**Comment by gmethvin** [comment]
I removed those imports because they were unused

**Comment by gmethvin** [comment]
would be good to have a new release for this btw @sksamuel

**Comment by sksamuel** [comment]
2.5.0 released.

**Pull request merged**
