### PR TITLE
Support more granular patternAutoDiscoveryPeriod

### PR DESCRIPTION
**Pull request by gmethvin**
Pulsar now supports periods as granular as seconds. This changes the API to use `FiniteDuration` instead of `Int` for clarity, and uses the new Pulsar builder API that supports `TimeUnit`

### CODE REVIEW

**Comment by sksamuel** [comment]
Breaking change, although a minor one. Maybe wait for 2.7.0 ?

**Comment by sksamuel** [comment]
2.7.0 is out so merging.

**Comment by gmethvin** [comment]
cool. should we do a new release for 2.7.0?

**Comment by sksamuel** [comment]
Yep, I can do that.

**Comment by sksamuel** [comment]
2.7.0 released.

**Pull request merged**
