### PR TITLE
feat: Async & Batch operations support

### PR DESCRIPTION
**Pull request by tonyvelichko**
Add async operations support for creating Consumer, Readers, and closing pulsar client. 
Add support for batch operations on the consumer-side.

### CODE REVIEW

**Comment by sksamuel** [comment]
I think this looks great. It's backwards compatible so no problems merging in. I'll wait to see if @gmethvin has an opinion before merging.

**Comment by gmethvin** [comment]
I agree, seems like a pretty good approach.

Can we add a few tests to verify that it works as intended?

**Comment by tonyvelichko** [comment]
> Can we add a few tests to verify that it works as intended?
Yeap will add them this week.

**Comment by tonyvelichko** [comment]
@gmethvin @sksamuel can you look into PR. I've changed a couple of things and now, all F methods are lazy.

**Review by gmethvin — APPROVED** [review]
lgtm

**Comment by tonyvelichko** [comment]
Guys, sorry for bothering you, do you have any ETA when these changes are going to be released?

**Comment by sksamuel** [comment]
2.7.2 released with these changes @tonyvelichko

**Comment by tonyvelichko** [comment]
Thanks! 😊

**Pull request merged**
