### PR TITLE
Support Avro schema versioning

### LINKED ISSUE #229: Implement Avro schema versioning to support backward compatibility
Here is a testcase showing that versioning of message is not implemented

```
import akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit
import akka.actor.typed.ActorRef
import com.sksamuel.pulsar4s.{ConsumerConfig, ProducerConfig, Subscription, Topic}
import org.apache.pulsar.client.api
import org.apache.pulsar.client.api.{SubscriptionInitialPosition, SubscriptionType}
import org.apache.pulsar.common.policies.data.SchemaCompatibilityStrategy
import org.scalatest.BeforeAndAfterEach
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpecLike

import scala.concurrent.duration._
import scala.util.Try

object v1 {
  case class Preferences(teams: Array[String])
}
object v2 {
  case class Preferences(teams: Array[String], acceptsAds: Option[Boolean]=None)
}
class PulsarSchemaVersion
    extends ScalaTestWithActorTestKit
    with Matchers
    with AnyWordSpecLike
    with BeforeAndAfterEach
    with PulsarSuite {

  var actors: Seq[ActorRef[_]] = _

  val pulsarTimeout: FiniteDuration = 1.minute
  val topic = Topic("persistent://public/default/devices")

  override protected def beforeEach(): Unit = {
    pulsarAdmin.namespaces().setSchemaCompatibilityStrategy("public/default", SchemaCompatibilityStrategy.BACKWARD_TRANSITIVE)
  }

  override protected def afterEach(): Unit = {
    pulsarClient.close()
    pulsarAdmin
      .topics()
      .delete(topic.name)
    pulsarAdmin.close()
  }
  import com.sksamuel.pulsar4s.avro._
  "updating schemas" should {
    "handle versioning" in {
      val producerv1 = pulsarClient.producer[v1.Preferences](
        ProducerConfig(
          topic = topic,
          producerName = Some("producer"),
          enableBatching = Some(false)
        )
      )

      producerv1.send(v1.Preferences(Array("OL", "OM")))
      producerv1.flush()
      producerv1.close()
      val consumer = pulsarClient.consumer[v2.Preferences](
        ConsumerConfig(
          subscriptionName = Subscription("subscription"),
          topics = Seq(topic),
          readCompacted = Some(false),
          consumerName = Some("consumer"),
          subscriptionType = Some(SubscriptionType.Shared),
          subscriptionInitialPosition =
            Some(SubscriptionInitialPosition.Earliest),
        )
      )
      val value1: Try[Option[v2.Preferences]] =
        consumer.receive(pulsarTimeout).map(_.map(_.value))

      value1.get.get should ===(
        v2.Preferences(Array("OL", "OM"), None)
      )
    }
  }
}
```

For the record, we did this small hack waiting for a proper implementation in pulsar4s:

```

object schemas {

  import com.sksamuel.pulsar4s.avro._

  def versionAwareAvroSchema[T: Manifest: SchemaFor: Encoder: Decoder]
      : PulsarSchema[T] =
    new PulsarSchema[T] {
      val schema: org.apache.avro.Schema = AvroSchema[T]

      override def clone(): PulsarSchema[T] = this

      private var schemaInfoProvider: Option[SchemaInfoProvider] = None
      override def setSchemaInfoProvider(
          schemaInfoProvider: SchemaInfoProvider
      ): Unit = this.schemaInfoProvider = Some(schemaInfoProvider)

      override def supportSchemaVersioning(): Boolean = true

      override def encode(t: T): Array[Byte] = {
        val baos = new ByteArrayOutputStream
        val aos = AvroOutputStream.binary[T].to(baos).build(schema)
        aos.write(t)
        aos.flush()
        aos.close()
        baos.toByteArray
      }

      private def decode(bytes: Array[Byte], schema: Schema): T = {
        val bais = new ByteArrayInputStream(bytes)
        val ais = AvroInputStream.binary[T].from(bais).build(schema)
        val first = ais.iterator.next()
        ais.close()
        first
      }

      override def decode(bytes: Array[Byte]): T = decode(bytes, this.schema)

      override def decode(
          bytes: Array[Byte],
          schemaVersion: Array[Byte]
      ): T = {
        val avroSchema: Option[Schema] = schemaInfoProvider.map(provider => {
          val infos: PulsarSchemaInfo =
            provider.getSchemaByVersion(schemaVersion).get()
          val parser = new org.apache.avro.Schema.Parser()
          parser.parse(infos.getSchemaDefinition)
        })
        avroSchema.fold(
          decode(bytes)
        )(schema => decode(bytes, schema))
      }

      override def getSchemaInfo: PulsarSchemaInfo =
        new PulsarSchemaInfo()
          .setName(manifest[T].runtimeClass.getCanonicalName)
          .setType(SchemaType.AVRO)
          .setSchema(schema.toString.getBytes(StandardCharsets.UTF_8))
    }

}
```

It would be great to have pulsar4s support for schema versioning.

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #229

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by mbaechler** [comment]
It looks good, thanks. I'll try it on my own project and keep you posted.

**Comment by gmethvin** [comment]
@mbaechler Not sure if this matters, but I realized my implementation of `clone` was incorrect. It needs to return a copy since the new implementation uses mutable state. I updated the code.

**Comment by mbaechler** [comment]
I just checked it seems to work fine.

**Comment by gmethvin** [comment]
Thanks @mbaechler. @sksamuel can you make a release for this?

**Comment by sksamuel** [comment]
Yep will do.

**Comment by sksamuel** [comment]
2.6.2 is released.

**Pull request merged**
