### PR TITLE
Implementation of getLastMessageId and getLastMessageIdAsync

### LINKED ISSUE #186: No implementation of consumer getLastMessageId()
The consumer implementation is missing of the following methods:

- getLastMessageId() 
- getLastMessageIdAsync() 

Please refer to https://github.com/apache/pulsar/blob/a50b75ac01754d80a75a230d44e96398f5e76661/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L539

### PR DESCRIPTION
**Pull request by nicolo-paganin**
fix #186

### CODE REVIEW

**Comment by gmethvin** [comment]
Thanks @nicolo-paganin! Can we add a test for this?

**Comment by nicolo-paganin** [comment]
@gmethvin tests added

**Comment by nicolo-paganin** [comment]
@gmethvin could you please publish a SNAPSHOT? :-)

**Comment by gmethvin** [comment]
That’s a question for @sksamuel

**Comment by sksamuel** [comment]
I'll release

**Comment by sksamuel** [comment]
Released 2.5.4

**Pull request merged**
