### PR TITLE
Upgrade pulsar to 2.7.1 and fix schema issues

### PR DESCRIPTION
**Pull request by gmethvin**
Update to Pulsar 2.7.1, and also change the schemas used by the JSON schemas to actually be valid. Since we are not actually doing validation for JSON, we can simply use the `BYTES` schema.

### CODE REVIEW

**Comment by gmethvin** [comment]
@sksamuel let me know if you have any thoughts/concerns on this. Also, not quite sure why the ZIO tests are failing...

**Comment by gmethvin** [comment]
@sksamuel This is a pretty important change for people wanting to upgrade to 2.7.1. The ZIO test failures seem probably unrelated so I might just merge as-is and go back to it later.

**Comment by sksamuel** [comment]
I'll review tonight. Sorry for the delay.

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
lgtm

**Comment by sksamuel** [comment]
I'll merge and see if I can fix the failing test.

**Pull request merged**
