### PR TITLE
Update zio and zio-interop-cats to 1.0.0-RC19

### PR DESCRIPTION
**Pull request by cipriansofronia**
Fixes #174 
Fixes #175

### CODE REVIEW

**Comment by cipriansofronia** [comment]
This fails as described here https://github.com/sksamuel/pulsar4s/pull/173#issuecomment-626980478

**Comment by sksamuel** [comment]
yeah I'm trying to figure out why its hanging in travis.

**Comment by sksamuel** [comment]
I have fixed master but there was one test in `CatsAsyncHandlerTest` that I had to disable as it was failing on a missing method exception. If you have time would you mind taking a look?

**Comment by cipriansofronia** [comment]
Will check :smile:

**Comment by sksamuel** [comment]
Thank you :)

**Comment by cipriansofronia** [comment]
Check #178

**Pull request merged**
