### PR TITLE
Support async creation of producers

### LINKED ISSUE #117: Support creating producers asynchronously
We should be able to create a Pulsar producer asynchronously using the `createAsync` method instead of `create` here: https://github.com/sksamuel/pulsar4s/blob/90f98e8/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/PulsarClient.scala#L144

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #117

### CODE REVIEW

**Comment by sksamuel** [comment]
On vacation at the moment. Can review sat. Or merge if you're happy with it.

**Comment by gmethvin** [comment]
@sksamuel That's fine, feel free to review this weekend. Then we should get a new release out after this is merged.

**Comment by gmethvin** [comment]
@sksamuel do you have time to take a look?

**Comment by sksamuel** [comment]
Sorry I had reviewed but forgot to click approve. Done now.

**Comment by gmethvin** [comment]
Thanks @sksamuel! Can we do a new release with this?

**Comment by sksamuel** [comment]
Yep, can do one tonight.

**Comment by sksamuel** [comment]
Some issues with doing a release.
I think probably 2.12 / 2.13 incompatibilities ?

[error]
/home/sam/development/workspace/pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/FutureAsyncHandler.scala:25:
no type parameters for method thenApply: (x$1:
java.util.function.Function[_ >: org.apache.pulsar.client.api.Producer[T],
_ <: U])java.util.concurrent.CompletableFuture[U] exist so that it can be
applied to arguments
(java.util.function.Function[org.apache.pulsar.client.api.Producer[T],com.sksamuel.pulsar4s.DefaultProducer[T]])
[error]  --- because ---
[error] argument expression's type is not compatible with formal parameter
type;
[error]  found   :
java.util.function.Function[org.apache.pulsar.client.api.Producer[T],com.sksamuel.pulsar4s.DefaultProducer[T]]
[error]  required: java.util.function.Function[_ >:
org.apache.pulsar.client.api.Producer[T], _ <: ?U]
[error] Note: org.apache.pulsar.client.api.Producer[T] <: Any, but
Java-defined trait Function is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: Any`.
(SLS 3.2.10)
[error]     builder.createAsync().thenApply(new DefaultProducer(_)).toScala
[error]                           ^
[error]
/home/sam/development/workspace/pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/FutureAsyncHandler.scala:25:
type mismatch;
[error]  found   :
java.util.function.Function[org.apache.pulsar.client.api.Producer[T],com.sksamuel.pulsar4s.DefaultProducer[T]]
[error]  required: java.util.function.Function[_ >:
org.apache.pulsar.client.api.Producer[T], _ <: U]
[error]     builder.createAsync().thenApply(new DefaultProducer(_)).toScala
[error]                                     ^
[error]
/home/sam/development/workspace/pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/FutureAsyncHandler.scala:25:
no type parameters for method thenApply: (x$1:
java.util.function.Function[_ >: org.apache.pulsar.client.api.Producer[T],
_ <: U])java.util.concurrent.CompletableFuture[U] exist so that it can be
applied to arguments
(java.util.function.Function[org.apache.pulsar.client.api.Producer[T],com.sksamuel.pulsar4s.DefaultProducer[T]])
[error]  --- because ---
[error] argument expression's type is not compatible with formal parameter
type;
[error]  found   :
java.util.function.Function[org.apache.pulsar.client.api.Producer[T],com.sksamuel.pulsar4s.DefaultProducer[T]]
[error]  required: java.util.function.Function[_ >:
org.apache.pulsar.client.api.Producer[T], _ <: ?U]
[error] Note: org.apache.pulsar.client.api.Producer[T] <: Any, but
Java-defined trait Function is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: Any`.
(SLS 3.2.10)
[error]     builder.createAsync().thenApply(new DefaultProducer(_)).toScala
[error]                           ^
[error]
/home/sam/development/workspace/pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/FutureAsyncHandler.scala:25:
type mismatch;
[error]  found   : scala.concurrent.Future[U]
[error]  required:
scala.concurrent.Future[com.sksamuel.pulsar4s.Producer[T]]
[error]     builder.createAsync().thenApply(new DefaultProducer(_)).toScala
[error]                                                             ^
[error]
/home/sam/development/workspace/pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/FutureAsyncHandler.scala:25:
type mismatch;
[error]  found   :
java.util.function.Function[org.apache.pulsar.client.api.Producer[T],com.sksamuel.pulsar4s.DefaultProducer[T]]
[error]  required: java.util.function.Function[_ >:
org.apache.pulsar.client.api.Producer[T], _ <: U]
[error]     builder.createAsync().thenApply(new DefaultProducer(_)).toScala
[error]                                     ^
[error]
/home/sam/development/workspace/pulsar4s/pulsar4s-core/src/main/scala/com/sksamuel/pulsar4s/FutureAsyncHandler.scala:25:
type mismatch;
[error]  found   : scala.concurrent.Future[U]
[error]  required:
scala.concurrent.Future[com.sksamuel.pulsar4s.Producer[T]]
[error]     builder.createAsync().thenApply(new DefaultProducer(_)).toScala
[error]                                                             ^
[error] three errors found
[info] No documentation generated with unsuccessful compiler run
[error] three errors found
[error] (pulsar4s-core/compile:doc) Scaladoc generation failed
[error] (pulsar4s-core/compile:compileIncremental) Compilation failed
[error] Total time: 25 s, completed 12-Jan-2020 17:17:45

**Pull request merged**
